pref("extensions.{e4a8a97b-f2ed-450b-b12d-ee082ba24781}.description", "chrome://greasemonkey/locale/greasemonkey.properties");
pref("extensions.greasemonkey.cors_csp_override.excludes", false);
pref("extensions.greasemonkey.cors_csp_override.excludes.value", "[\"\"]");
pref("extensions.greasemonkey.cors_csp_override.includes", false);
pref("extensions.greasemonkey.cors_csp_override.includes.value", "[\"*\"]");
pref("extensions.greasemonkey.cors_csp_override.matches", false);
pref("extensions.greasemonkey.cors_csp_override.matches.value", "[\"\"]");
pref("extensions.greasemonkey.cors_override", false);
pref("extensions.greasemonkey.cors_override.[all]", false);
pref("extensions.greasemonkey.cors_override.access-control-allow-headers", false);
pref("extensions.greasemonkey.cors_override.access-control-allow-methods", false);
pref("extensions.greasemonkey.cors_override.access-control-allow-origin", false);
pref("extensions.greasemonkey.cors_override.access-control-expose-headers", false);
pref("extensions.greasemonkey.cors_override.x-content-type-options", false);
pref("extensions.greasemonkey.cors_override.x-frame-options", false);
pref("extensions.greasemonkey.csp_override", false);
pref("extensions.greasemonkey.csp_override.[all].[all-allow]", false);
pref("extensions.greasemonkey.csp_override.[all].[source-list]", false);
pref("extensions.greasemonkey.csp_override.[all].[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.[all].unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.[all].unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.base-uri.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.base-uri.[source-list]", false);
pref("extensions.greasemonkey.csp_override.base-uri.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.base-uri.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.base-uri.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.block-all-mixed-content.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.child-src.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.child-src.[source-list]", false);
pref("extensions.greasemonkey.csp_override.child-src.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.child-src.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.child-src.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.connect-src.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.connect-src.[source-list]", false);
pref("extensions.greasemonkey.csp_override.connect-src.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.connect-src.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.connect-src.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.default-src.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.default-src.[source-list]", false);
pref("extensions.greasemonkey.csp_override.default-src.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.default-src.strict-dynamic", false);
pref("extensions.greasemonkey.csp_override.default-src.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.default-src.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.font-src.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.font-src.[source-list]", false);
pref("extensions.greasemonkey.csp_override.font-src.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.font-src.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.font-src.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.form-action.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.form-action.[source-list]", false);
pref("extensions.greasemonkey.csp_override.form-action.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.form-action.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.form-action.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.frame-ancestors.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.frame-ancestors.[source-list]", false);
pref("extensions.greasemonkey.csp_override.frame-ancestors.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.frame-ancestors.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.frame-ancestors.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.frame-src.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.frame-src.[source-list]", false);
pref("extensions.greasemonkey.csp_override.frame-src.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.frame-src.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.frame-src.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.img-src.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.img-src.[source-list]", false);
pref("extensions.greasemonkey.csp_override.img-src.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.img-src.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.img-src.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.manifest-src.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.manifest-src.[source-list]", false);
pref("extensions.greasemonkey.csp_override.manifest-src.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.manifest-src.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.manifest-src.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.media-src.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.media-src.[source-list]", false);
pref("extensions.greasemonkey.csp_override.media-src.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.media-src.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.media-src.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.object-src.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.object-src.[source-list]", false);
pref("extensions.greasemonkey.csp_override.object-src.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.object-src.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.object-src.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.plugin-types.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.refferer.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.reflected-xss.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.report-uri.[all-allow]", true);
pref("extensions.greasemonkey.csp_override.require-sri-for.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.sandbox.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.sandbox.allow-forms", false);
pref("extensions.greasemonkey.csp_override.sandbox.allow-pointer-lock", false);
pref("extensions.greasemonkey.csp_override.sandbox.allow-popups", false);
pref("extensions.greasemonkey.csp_override.sandbox.allow-same-origin", false);
pref("extensions.greasemonkey.csp_override.sandbox.allow-scripts", false);
pref("extensions.greasemonkey.csp_override.sandbox.allow-top-navigation", false);
pref("extensions.greasemonkey.csp_override.script-src.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.script-src.[source-list]", false);
pref("extensions.greasemonkey.csp_override.script-src.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.script-src.strict-dynamic", false);
pref("extensions.greasemonkey.csp_override.script-src.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.script-src.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.style-src.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.style-src.[source-list]", false);
pref("extensions.greasemonkey.csp_override.style-src.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.style-src.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.style-src.unsafe-inline", false);
pref("extensions.greasemonkey.csp_override.upgrade-insecure-requests.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.worker-src.[all-allow]", false);
pref("extensions.greasemonkey.csp_override.worker-src.[source-list]", false);
pref("extensions.greasemonkey.csp_override.worker-src.[source-list].value", "blob: data:");
pref("extensions.greasemonkey.csp_override.worker-src.unsafe-eval", false);
pref("extensions.greasemonkey.csp_override.worker-src.unsafe-inline", false);
pref("extensions.greasemonkey.dataIsGreaseable", false);
pref("extensions.greasemonkey.enableScriptRefreshing", true);
pref("extensions.greasemonkey.enqueuedRemovals", "[]");
pref("extensions.greasemonkey.fileDependencyUrlIsDescendantOfDownloadUrl", false);
pref("extensions.greasemonkey.fileIsGreaseable", false);
pref("extensions.greasemonkey.globalExcludes", "[]");
pref("extensions.greasemonkey.haveInsertedToolbarbutton", false);
pref("extensions.greasemonkey.installDelay", 5);
pref("extensions.greasemonkey.jarIsGreaseable", false);
pref("extensions.greasemonkey.newScript.removeUnused", true);
pref("extensions.greasemonkey.newScript.template", "// ==UserScript==\n// @name        %name%\n// @namespace   %namespace%\n// @description %description%\n// @include     %include%\n// @exclude     %exclude%\n// @version     1\n// @grant       none\n// ==/UserScript==");
pref("extensions.greasemonkey.requireDisabledScriptsUpdates", false);
pref("extensions.greasemonkey.requireSecureUpdates", true);
pref("extensions.greasemonkey.requireTimeoutUpdates", true);
pref("extensions.greasemonkey.showGrantsWarning", true);
pref("extensions.greasemonkey.sniffGrants", false);
pref("extensions.greasemonkey.sortBy", "uiState,name");
pref("extensions.greasemonkey.stats.id", "");
pref("extensions.greasemonkey.stats.interval", 604800000); // ms = 1 week
pref("extensions.greasemonkey.stats.lastSubmitTime", "Thu, 01 Jan 1970 00:00:00 GMT");
pref("extensions.greasemonkey.stats.optedIn", false);
pref("extensions.greasemonkey.stats.prompted", false);
pref("extensions.greasemonkey.stats.url", "https://stats.greasespot.net/submit/");
pref("extensions.greasemonkey.sync.enabled", true);
pref("extensions.greasemonkey.sync.values", false);
pref("extensions.greasemonkey.sync.values_maxSizePerScript", 65536);
pref("extensions.greasemonkey.timeoutUpdatesInSeconds", 45);
pref("extensions.greasemonkey.unmhtIsGreaseable", false);
pref("extensions.greasemonkey.version", "0.0");
pref("services.sync.prefs.sync.extensions.greasemonkey.enableScriptRefreshing", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.globalExcludes", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.newScript.removeUnused", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.newScript.template", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.requireSecureUpdates", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.requireTimeoutUpdates", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.showGrantsWarning", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.stats.lastSubmitTime", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.stats.optedIn", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.sync.enabled", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.sync.values", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.timeoutUpdatesInSeconds", true);
